jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
          docker build -t "$IMAGE:${GITHUB_SHA:0:7}" .
          docker push "$IMAGE:${GITHUB_SHA:0:7}"
        env:
          REGISTRY: ${{ vars.REGISTRY }}
          REGISTRY_PASSWORD: ${{ vars.REGISTRY_PASSWORD }}
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          APP_NAME: ${{ vars.APP_NAME }}
          IMAGE: ${{ vars.REGISTRY }}/${{ vars.APP_NAME }}
  darkube_deploy:
    needs: build
    container: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: darkube deploy --ref master --token ${DARKUBE_DEPLOY_TOKEN} --app-id ${DARKUBE_APP_ID}  --image-tag "${GITHUB_SHA:0:7}" --job-id "$GITHUB_JOB" --stateless-app true
        env:
          DARKUBE_DEPLOY_TOKEN: ${{ vars.DARKUBE_DEPLOY_TOKEN }}
          DARKUBE_APP_ID: ${{ vars.DARKUBE_APP_ID }}

name: CI/CD Pipeline
"on":
  push:
    branches:
      - master
